### ISSUE TITLE
Illegible styling on pre-HoneyComb devices

### ISSUE THREAD

**Issue by rtyley** [gaugesapp/gauges-android#1]
For pre-HoneyComb Android (ie before v3.0) the styling is bad on the sign-in page - although the hint-text is visible, once text is entered it's white on a white background:

![email address and password are in white text on a white background](https://img.skitch.com/20120128-ny78d22g9a59st1hk5ajbr4yxk.jpg)

We want to keep ICS styling as much as possible but tweak based on platform version: 

http://developer.android.com/guide/topics/ui/themes.html#SelectATheme

**Comment by kevinsawicki** [comment]
Yeah, this was a mistake on my part.

You shouldn't set an explicit text color on text input fields right? Since they can have different native styling on each platform.

I'll remove the explicit text color attribute so it will default to the platform default

**Comment by rtyley** [comment]
This animated gif is from a recent build on froyo - the sign-in text is fine, closing this issue:

![Froyo](http://f.cl.ly/items/0E150W060b3s3Z1V0C2X/emulator-5554_FroyoPojo_unknown_google_sdk.gif)

**Comment by kevinsawicki** [comment]
This is still an issue on the Kindle Fire (Gingerbread)

![](http://img.skitch.com/20120213-jkh4tfbknsgegew8f28dcm28qa.png)

**Comment by kevinsawicki** [comment]
I'm closing this out since we are explicitly styling these fields now and they shouldn't vary based on platform
