### ISSUE TITLE
Can't exit application hitting 'back' from login screen

### ISSUE THREAD

**Issue by luislavena** [gaugesapp/gauges-android#15]
Hello,

I didn't have a Gaug.es account so when installed it and asked for credentials, decided to exit and signup from my laptop.

But application didn't quit when pressing `back` button on my phone (Samsung Galaxy S II, Android 2.3.5)

So I ended killing the application from the task manager because going back to exit wasn't possible.

I minor nitpick.

Thank you.

**Comment by rtyley** [comment]
Hi @luislavena you're right, it's not great behaviour there - the back button takes you back to the main activity, which requires a login and so puts you back on the sign-in screen. We need a 'Welcome' activity that doesn't require a signed-in user to make the user experience better here.

As a workaround, using the 'Home' key should get you back to your home screen? The Gaug.es app wouldn't immediately exit but the Android OS should shut it down after a period of inactivity.

**Comment by luislavena** [comment]
@rtyley that is correct, 'home' button goes what it suppose to do, but wanted to mention this as part of the UX.

I think saying _needed to kill the app_ was too dramatic, but got your attention :wink:

Either way, wanted to report this before I forgot. I haven't done any Android development before to contribute back and I'm sorry open issues without a solution :cry:

**Comment by kevinsawicki** [comment]
This has been fixed in master in commit 0364c5e744e43449eb766348a6bdfcfa6491f59c
