### ISSUE TITLE
Visual indication of reloading-stats

### ISSUE THREAD

**Issue by rtyley** [gaugesapp/gauges-android#8]
At the moment when you hit the reload button there's not really any visual indication that anything's going on - we should probably turn the reload button into a spinning-circle animation while loading.

**Comment by rtyley** [comment]
There's an example of this behaviour when reloading the google plus activity stream in the google-plus android app - think that's the canonical image, I'm just not sure where we can get a copy.

**Comment by rtyley** [comment]
Looks like this rotating drawable is progress_small_holo:

https://github.com/android/platform_frameworks_base/blob/master/core/res/res/drawable/progress_small_holo.xml

Given the apache licensing, we should be okay to take a copy and use this in our own app

**Comment by EddieRingle** [comment]
Why not set an ActionView on the refresh menu item when it is clicked, and removing it when the loading is complete? You could attach an ImageView to it using the same drawable but include a rotate animation.

**Comment by kevinsawicki** [comment]
Thanks @eddieringle  for fixing this.
